# Generated by Django 5.2 on 2025-04-17 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Semla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bakery', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('picture', models.CharField(default='/images/', max_length=255)),
                ('vegan', models.BooleanField(default=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=3)),
                ('kind', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Ratings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('comment', models.TextField()),
                ('semla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='semelVoter.semla')),
            ],
        ),
    ]
