# Generated by Django 5.2 on 2025-04-17 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semelVoter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semla',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
