# Generated by Django 5.2 on 2025-04-17 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semelVoter', '0002_alter_semla_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratings',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='semla',
            name='picture',
            field=models.CharField(max_length=255),
        ),
    ]
