# Generated by Django 5.2 on 2025-04-17 20:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semelVoter', '0003_alter_ratings_comment_alter_semla_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratings',
            name='date',
            field=models.DateTimeField(default=datetime.date.today),
        ),
    ]
