# Generated by Django 5.2 on 2025-04-17 20:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semelVoter', '0004_ratings_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratings',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
