# Generated by Django 5.2 on 2025-04-17 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semelVoter', '0006_semla_votes'),
    ]

    operations = [
        migrations.AddField(
            model_name='semla',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
    ]
