# Generated by Django 5.2 on 2025-04-17 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semelVoter', '0007_semla_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semla',
            name='votes',
        ),
        migrations.AlterField(
            model_name='semla',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
    ]
