# Generated by Django 5.2 on 2025-04-18 11:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semelVoter', '0008_remove_semla_votes_alter_semla_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratings',
            name='date',
            field=models.DateField(default=datetime.date(2025, 4, 18)),
        ),
        migrations.CreateModel(
            name='RatingTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=45)),
                ('user_agent', models.TextField()),
                ('date', models.DateField(default=datetime.date.today)),
                ('count', models.PositiveIntegerField(default=1)),
            ],
            options={
                'unique_together': {('ip_address', 'user_agent', 'date')},
            },
        ),
    ]
