# Generated by Django 5.2 on 2025-04-19 07:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semelVoter', '0009_alter_ratings_date_ratingtracker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratings',
            name='date',
            field=models.DateField(default=datetime.date(2025, 4, 19)),
        ),
    ]
