# Generated by Django 5.2 on 2026-01-28 12:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semelVoter', '0010_alter_ratings_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratings',
            name='date',
            field=models.DateField(default=datetime.date(2026, 1, 28)),
        ),
    ]
