# Generated by Django 5.2 on 2026-01-28 12:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semelVoter', '0011_alter_ratings_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratings',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
