# Generated by Django 5.2 on 2026-01-29 20:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semelVoter', '0012_alter_ratings_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratingtracker',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='semla',
            name='picture',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
