# Generated by Django 5.2 on 2026-01-29 21:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semelVoter', '0013_allow_blank_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='SemlaCreationTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=45)),
                ('user_agent', models.TextField()),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('count', models.PositiveIntegerField(default=1)),
            ],
            options={
                'unique_together': {('ip_address', 'user_agent', 'date')},
            },
        ),
    ]
