# Generated by Django 5.2 on 2026-01-30 13:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semelVoter', '0014_add_semla_creation_tracker'),
    ]

    operations = [
        migrations.CreateModel(
            name='SemlaImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image_url', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('semla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='semelVoter.semla')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
