# Generated by Django 5.2 on 2026-01-31 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semelVoter', '0015_add_semla_image_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratings',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
