# Generated by Django 5.2 on 2026-02-01 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semelVoter', '0016_add_name_to_ratings'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratings',
            name='bulle',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ratings',
            name='gradde',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ratings',
            name='helhet',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ratings',
            name='lock',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ratings',
            name='mandelmassa',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
